## Assignment 3

**TU Delft and WUR**<br>
**Q1 2024**<br>
**Instructor:** Theodoros Chatzivasileiadis <br>
**Instructor:** Hans Hoogenboom <br>
**TA:** Ka Yi Chua <br>
**[Metropolitan Data 1](https://jhoogenboom.github.io/spatial-data-science/_index.html)** <br>

__This homework assignment document will guide you through five tasks in cleaning your data.__

1. Reading and Summarizing the Data.
2. Subsetting the Data.
3. Manage Missing Data.
4. Shape the Data.
5. Saving the Results. 

# NB: From now on you should submit 1) your notebook with the answers, remember that comments are good practice, 2) a working Git page with your assignment

## Exercise 1: Loading the data:

- Load the `goodreads.csv` file into Python
- Explore it by looking at first and last 5 rows
- Change the column names to `["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name']`

In [29]:
# your code here
# use many cells if you like to structure your code well
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 30)

In [30]:
#Read the data into a dataframe
df = pd.read_csv("./data/goodreads.csv", encoding='utf-8')

#Examine the first few rows of the dataframe
df

      4.40   136455  0439023483  good_reads:book https://www.goodreads.com/author/show/153394.Suzanne_Collins    2008 /genres/young-adult|/genres/science-fiction|/genres/dystopia|/genres/fantasy|/genres/science-fiction|/genres/romance|/genres/adventure|/genres/book-club|/genres/young-adult|/genres/teen|/genres/apocalyptic|/genres/post-apocalyptic|/genres/action                dir01/2767052-the-hunger-games.html    2958974            The Hunger Games (The Hunger Games, #1)
0     4.41  16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....            2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...                                                                                                                                                                                                     dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...  1284478.0  Harry Potter and the Order of the Phoenix (Har...
1     3.56  85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...            2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                                                                                                                                                                                                                             dir01/41865.Twilight.html  2579564.0                            Twilight (Twilight, #1)
2     4.23  47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...            1960.0  /genres/classics|/genres/fiction|/genres/histo...                                                                                                                                                                                                                 dir01/2657.To_Kill_a_Mockingbird.html  2078123.0                              To Kill a Mockingbird
3     4.23  34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...            1813.0  /genres/classics|/genres/fiction|/genres/roman...                                                                                                                                                                                                                   dir01/1885.Pride_and_Prejudice.html  1388992.0                                Pride and Prejudice
4     4.25  12363.0  0446675539  good_reads:book  https://www.goodreads.com/author/show/11081.Ma...            1936.0  /genres/classics|/genres/historical-fiction|/g...                                                                                                                                                                                                                   dir01/18405.Gone_with_the_Wind.html   645470.0                                 Gone with the Wind
...    ...      ...         ...              ...                                                ...               ...                                                ...                                                                                                                                                                                                                                                   ...        ...                                                ...
5994  4.17   2226.0  0767913736  good_reads:book  https://www.goodreads.com/author/show/44565.Ca...            2005.0  /genres/history|/genres/non-fiction|/genres/bi...                                                                                                                                                                                                                   dir60/78508.The_River_of_Doubt.html    16618.0                                 The River of Doubt
5995  3.99    775.0  1416909427  good_reads:book  https://www.goodreads.com/author/show/151371.J...            2006.0  /genres/young-adult|/genres/realistic-fiction|...                                                                                                                                                                                                                                dir60/259068.Shug.html     6179.0                                               Shug
5996  3.78    540.0  1620612321  good_reads:book  https://www.goodreads.com/author/show/5761314....            2012.0  /genres/contemporary|/genres/romance|/genres/y...                                                                                                                                                                                                                            dir60/13503247-flawed.html     2971.0                                             Flawed
5997  3.91    281.0         NaN  good_reads:book  https://www.goodreads.com/author/show/1201952....            2006.0  /genres/religion|/genres/islam|/genres/religio...                                                                                                                                                                                                                                    dir60/2750008.html     3083.0              Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ

5998  4.35     61.0  0786929081  good_reads:book  https://www.goodreads.com/author/show/1023510....            2001.0  /genres/fiction|/genres/fantasy|/genres/magic|...                                                                                                                                                                                                     dir60/66677.Legacy_of_the_Drow_Collector_s_Edi...     3982.0  Legacy of the Drow Collector's Edition (Legacy...

[5999 rows x 10 columns]

In [31]:
df=pd.read_csv("data/goodreads.csv", header=None,
               names=["rating", 'review_count', 'isbn', 'booktype','author_url', 'year', 'genre_urls', 'dir','rating_count', 'name'],
)

#Examine the first few rows of the dataframe
df.head()

   rating  review_count        isbn         booktype                                         author_url    year                                         genre_urls                                                dir  rating_count                                               name
0    4.40      136455.0  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...                dir01/2767052-the-hunger-games.html     2958974.0            The Hunger Games (The Hunger Games, #1)
1    4.41       16648.0  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...     1284478.0  Harry Potter and the Order of the Phoenix (Har...
2    3.56       85746.0  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                          dir01/41865.Twilight.html     2579564.0                            Twilight (Twilight, #1)
3    4.23       47906.0  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...              dir01/2657.To_Kill_a_Mockingbird.html     2078123.0                              To Kill a Mockingbird
4    4.23       34772.0  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                dir01/1885.Pride_and_Prejudice.html     1388992.0                                Pride and Prejudice

## Exercise 2: Subsetting the data

- Subset the data by creating new dataframe only with `["rating", 'isbn', 'author_url', 'year', 'genre_urls', 'name']`

In [32]:
df_new = df.drop(columns=["review_count", "booktype", "dir", "rating_count"])
df_new

      rating        isbn                                         author_url    year                                         genre_urls                                               name
0       4.40  0439023483  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...            The Hunger Games (The Hunger Games, #1)
1       4.41  0439358078  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  Harry Potter and the Order of the Phoenix (Har...
2       3.56  0316015849  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                            Twilight (Twilight, #1)
3       4.23  0061120081  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...                              To Kill a Mockingbird
4       4.23  0679783261  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                                Pride and Prejudice
...      ...         ...                                                ...     ...                                                ...                                                ...
5995    4.17  0767913736  https://www.goodreads.com/author/show/44565.Ca...  2005.0  /genres/history|/genres/non-fiction|/genres/bi...                                 The River of Doubt
5996    3.99  1416909427  https://www.goodreads.com/author/show/151371.J...  2006.0  /genres/young-adult|/genres/realistic-fiction|...                                               Shug
5997    3.78  1620612321  https://www.goodreads.com/author/show/5761314....  2012.0  /genres/contemporary|/genres/romance|/genres/y...                                             Flawed
5998    3.91         NaN  https://www.goodreads.com/author/show/1201952....  2006.0  /genres/religion|/genres/islam|/genres/religio...              Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ

5999    4.35  0786929081  https://www.goodreads.com/author/show/1023510....  2001.0  /genres/fiction|/genres/fantasy|/genres/magic|...  Legacy of the Drow Collector's Edition (Legacy...

[6000 rows x 6 columns]

In [33]:
# your code here
# use many cells if you like to structure your code well
df_new.dtypes

rating        float64
isbn           object
author_url     object
year          float64
genre_urls     object
name           object
dtype: object

In [34]:
#Get a sense of how many missing values there are in the dataframe.
print(np.sum([df_new.rating.isnull()]))
print(np.sum([df_new.isbn.isnull()]))
print(np.sum([df_new.author_url.isnull()]))
print(np.sum([df_new.year.isnull()]))
print(np.sum([df_new.genre_urls.isnull()]))
print(np.sum([df_new.name.isnull()]))

2
477
2
7
62
2

In [35]:
df_new[df_new.rating.isnull()]

      rating isbn author_url  year genre_urls name
3643     NaN  NaN        NaN   NaN        NaN  NaN
5282     NaN  NaN        NaN   NaN        NaN  NaN

In [36]:
df_new[df_new.isbn.isnull()]

      rating isbn                                         author_url    year                                         genre_urls                                   name
16      3.92  NaN  https://www.goodreads.com/author/show/498072.A...  2003.0  /genres/fiction|/genres/romance|/genres/fantas...               The Time Traveler's Wife
49      3.85  NaN  https://www.goodreads.com/author/show/5152.Vla...  1955.0  /genres/classics|/genres/fiction|/genres/liter...                                 Lolita
85      4.16  NaN  https://www.goodreads.com/author/show/137902.R...  2007.0  /genres/young-adult|/genres/teen|/genres/young...  Vampire Academy (Vampire Academy, #1)
116     3.92  NaN  https://www.goodreads.com/author/show/957894.A...  1942.0  /genres/classics|/genres/fiction|/genres/philo...                           The Stranger
156     4.03  NaN  https://www.goodreads.com/author/show/4785.Ale...  1843.0  /genres/classics|/genres/fiction|/genres/histo...                   The Three Musketeers
...      ...  ...                                                ...     ...                                                ...                                    ...
5972    4.19  NaN  https://www.goodreads.com/author/show/4586597....  2011.0  /genres/romance|/genres/romance|/genres/contem...    Perfection (Neighbor from Hell, #2)
5976    4.23  NaN  https://www.goodreads.com/author/show/5160667....  2014.0  /genres/romance|/genres/science-fiction|/genre...                          Transcendence
5977    4.03  NaN  https://www.goodreads.com/author/show/5769580....  1987.0  /genres/fiction|/genres/novels|/genres/literat...                             Ø§ÙØªÙÙ
5991    4.20  NaN    https://www.goodreads.com/author/show/1112683._  2009.0  /genres/novels|/genres/fiction|/genres/religio...                    Ø£ÙÙØ§Ø­ ÙØ¯Ø³Ø±
5998    3.91  NaN  https://www.goodreads.com/author/show/1201952....  2006.0  /genres/religion|/genres/islam|/genres/religio...  Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ


[477 rows x 6 columns]

In [37]:
df_new[df_new.author_url.isnull()]

      rating isbn author_url  year genre_urls name
3643     NaN  NaN        NaN   NaN        NaN  NaN
5282     NaN  NaN        NaN   NaN        NaN  NaN

In [38]:
df_new[df_new.year.isnull()]

      rating        isbn                                         author_url  year                                         genre_urls                                               name
2442    4.23         NaN  https://www.goodreads.com/author/show/623606.A...   NaN  /genres/religion|/genres/islam|/genres/non-fic...                                          La Tahzan
2869    4.61         NaN  https://www.goodreads.com/author/show/8182217....   NaN                                                NaN  My Death Experiences - A Preacherâs 18 Apoca...
3643     NaN         NaN                                                NaN   NaN                                                NaN                                                NaN
5282     NaN         NaN                                                NaN   NaN                                                NaN                                                NaN
5572    3.71  8423336603  https://www.goodreads.com/author/show/285658.E...   NaN                                    /genres/fiction  Ãrase una vez el amor pero tuve que matarlo. ...
5658    4.32         NaN  https://www.goodreads.com/author/show/25307.Ro...   NaN  /genres/fantasy|/genres/fantasy|/genres/epic-f...  Assassin's Apprentice / Royal Assassin (Farsee...
5683    4.56         NaN  https://www.goodreads.com/author/show/3097905....   NaN  /genres/fantasy|/genres/young-adult|/genres/ro...                 Tiger's Dream (The Tiger Saga, #5)

In [39]:
df_new[df_new.genre_urls.isnull()]

      rating        isbn                                         author_url    year genre_urls                                               name
953     4.56  1477276068  https://www.goodreads.com/author/show/6621980....  2012.0        NaN                                  Crossing the Seas
1515    4.56         NaN  https://www.goodreads.com/author/show/394525.T...  2013.0        NaN                             Crashing Down to Earth
1693    4.21         NaN    https://www.goodreads.com/author/show/3110785._  2009.0        NaN                Ð¡Ð»ÑÐ½ÑÐµ Ð½ÐµÐ´Ð¾ÑÐµÐ³Ð°ÐµÐ¼Ð¾
1752    3.85  140921818X  https://www.goodreads.com/author/show/7337562....    13.0        NaN                    The Day Jesus Rode Into Croydon
1942    4.66  0992382009  https://www.goodreads.com/author/show/7574275....  2014.0        NaN                             Letters from your soul
...      ...         ...                                                ...     ...        ...                                                ...
5618    4.44  1495907791  https://www.goodreads.com/author/show/7399883....  2014.0        NaN                        The Afternoon When She Died
5692    5.00         NaN  https://www.goodreads.com/author/show/5989528....  2012.0        NaN  Abstraction In Theory - Laws Of Physical Trans...
5717    4.71         NaN  https://www.goodreads.com/author/show/5838022....  2012.0        NaN                                  American Amaranth
5729    4.83         NaN  https://www.goodreads.com/author/show/7058502....  2014.0        NaN                        The Keeper (The Keeper, #5)
5778    4.63         NaN  https://www.goodreads.com/author/show/4808225....  2010.0        NaN                                        (Un) Spoken

[62 rows x 6 columns]

In [40]:
df_new[df_new.name.isnull()]

      rating isbn author_url  year genre_urls name
3643     NaN  NaN        NaN   NaN        NaN  NaN
5282     NaN  NaN        NaN   NaN        NaN  NaN

## Exercise 3: Manage Missing Data
We’ve got a number of ways in general of dealing with missing data. These involve

1. Dropping off cases (or rows) in the data with any missing variables
2. Excluding variables in the data with any missing data 
3. Selectively choosing indicators with only a limited amount of missing data
4. Replacing missing variables with averages, or other representative values
5. Creating a separate model to predict missing data

- Count the missing values in each column
- Manage the missing values (delete or replace values or leave them as they are) and briefly explain your choice for each column

In [41]:
# your code here
# use many cells if you like to structure your code well
df_new.dtypes

rating        float64
isbn           object
author_url     object
year          float64
genre_urls     object
name           object
dtype: object

In [42]:
df_new[pd.isnull(df_new.rating)]

      rating isbn author_url  year genre_urls name
3643     NaN  NaN        NaN   NaN        NaN  NaN
5282     NaN  NaN        NaN   NaN        NaN  NaN

In [43]:
df_new.drop([3643,5282]) #drop these two rows, because there's no information, found on (https://pandas.pydata.org/pandas-docs/dev/reference/api/pandas.DataFrame.drop.html)
# author_url and name missings are dealt with too, because these were the same rows

      rating        isbn                                         author_url    year                                         genre_urls                                               name
0       4.40  0439023483  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...            The Hunger Games (The Hunger Games, #1)
1       4.41  0439358078  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  Harry Potter and the Order of the Phoenix (Har...
2       3.56  0316015849  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                            Twilight (Twilight, #1)
3       4.23  0061120081  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...                              To Kill a Mockingbird
4       4.23  0679783261  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                                Pride and Prejudice
...      ...         ...                                                ...     ...                                                ...                                                ...
5995    4.17  0767913736  https://www.goodreads.com/author/show/44565.Ca...  2005.0  /genres/history|/genres/non-fiction|/genres/bi...                                 The River of Doubt
5996    3.99  1416909427  https://www.goodreads.com/author/show/151371.J...  2006.0  /genres/young-adult|/genres/realistic-fiction|...                                               Shug
5997    3.78  1620612321  https://www.goodreads.com/author/show/5761314....  2012.0  /genres/contemporary|/genres/romance|/genres/y...                                             Flawed
5998    3.91         NaN  https://www.goodreads.com/author/show/1201952....  2006.0  /genres/religion|/genres/islam|/genres/religio...              Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ

5999    4.35  0786929081  https://www.goodreads.com/author/show/1023510....  2001.0  /genres/fiction|/genres/fantasy|/genres/magic|...  Legacy of the Drow Collector's Edition (Legacy...

[5998 rows x 6 columns]

In [44]:
df_new.isbn.fillna("Unknown") #It's only one column that doesn't really have informational value, so i replaced it with unknown

0       0439023483
1       0439358078
2       0316015849
3       0061120081
4       0679783261
           ...
5995    0767913736
5996    1416909427
5997    1620612321
5998       Unknown
5999    0786929081
Name: isbn, Length: 6000, dtype: object

In [45]:
df_new.year.fillna("Unknown")

0       2008.0
1       2003.0
2       2005.0
3       1960.0
4       1813.0
         ...
5995    2005.0
5996    2006.0
5997    2012.0
5998    2006.0
5999    2001.0
Name: year, Length: 6000, dtype: object

In [46]:
df_new.genre_urls.fillna("Unknown")

0       /genres/young-adult|/genres/science-fiction|/g...
1       /genres/fantasy|/genres/young-adult|/genres/fi...
2       /genres/young-adult|/genres/fantasy|/genres/ro...
3       /genres/classics|/genres/fiction|/genres/histo...
4       /genres/classics|/genres/fiction|/genres/roman...
                              ...
5995    /genres/history|/genres/non-fiction|/genres/bi...
5996    /genres/young-adult|/genres/realistic-fiction|...
5997    /genres/contemporary|/genres/romance|/genres/y...
5998    /genres/religion|/genres/islam|/genres/religio...
5999    /genres/fiction|/genres/fantasy|/genres/magic|...
Name: genre_urls, Length: 6000, dtype: object

In [53]:

# Dropping rows where all values are missing
df_cleaned = df_new.dropna(how='all')

# Replacing all remaining missing values with "unknown"
df_cleaned.fillna('unknown', inplace=True)

#Replace missing values in numerical columns with 0
numerical_cols = df_cleaned.select_dtypes(include=['float64', 'int64']).columns
df_cleaned[numerical_cols] = df_cleaned[numerical_cols].fillna(0)

# Replace missing values in non-numerical columns with "unknown"
non_numerical_cols = df_cleaned.select_dtypes(exclude=['float64', 'int64']).columns
df_cleaned[non_numerical_cols] = df_cleaned[non_numerical_cols].fillna('unknown')


print(df_cleaned)

      rating        isbn                                         author_url    year                                         genre_urls                                               name
0       4.40  0439023483  https://www.goodreads.com/author/show/153394.S...  2008.0  /genres/young-adult|/genres/science-fiction|/g...            The Hunger Games (The Hunger Games, #1)
1       4.41  0439358078  https://www.goodreads.com/author/show/1077326....  2003.0  /genres/fantasy|/genres/young-adult|/genres/fi...  Harry Potter and the Order of the Phoenix (Har...
2       3.56  0316015849  https://www.goodreads.com/author/show/941441.S...  2005.0  /genres/young-adult|/genres/fantasy|/genres/ro...                            Twilight (Twilight, #1)
3       4.23  0061120081  https://www.goodreads.com/author/show/1825.Har...  1960.0  /genres/classics|/genres/fiction|/genres/histo...                              To Kill a Mockingbird
4       4.23  0679783261  https://www.goodreads.com/author/show/1265.Jan...  1813.0  /genres/classics|/genres/fiction|/genres/roman...                                Pride and Prejudice
...      ...         ...                                                ...     ...                                                ...                                                ...
5995    4.17  0767913736  https://www.goodreads.com/author/show/44565.Ca...  2005.0  /genres/history|/genres/non-fiction|/genres/bi...                                 The River of Doubt
5996    3.99  1416909427  https://www.goodreads.com/author/show/151371.J...  2006.0  /genres/young-adult|/genres/realistic-fiction|...                                               Shug
5997    3.78  1620612321  https://www.goodreads.com/author/show/5761314....  2012.0  /genres/contemporary|/genres/romance|/genres/y...                                             Flawed
5998    3.91     unknown  https://www.goodreads.com/author/show/1201952....  2006.0  /genres/religion|/genres/islam|/genres/religio...              Ø£Ø³Ø¹Ø¯ Ø§ÙØ±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ
5999    4.35  0786929081  https://www.goodreads.com/author/show/1023510....  2001.0  /genres/fiction|/genres/fantasy|/genres/magic|...  Legacy of the Drow Collector's Edition (Legacy...

[5998 rows x 6 columns]

C:\Users\bartl\AppData\Local\Temp\ipykernel_23964\1044733081.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_cleaned.fillna('unknown', inplace=True)
C:\Users\bartl\AppData\Local\Temp\ipykernel_23964\1044733081.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned.fillna('unknown', inplace=True)
C:\Users\bartl\AppData\Local\Temp\ipykernel_23964\1044733081.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[numerical_cols] = df_cleaned[numerical_cols].fillna(0)
C:\Users\bartl\AppData\Local\Temp\ipykernel_23964\1044733081.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned[non_numerical_cols] = df_cleaned[non_numerical_cols].fillna('unknown')

## Exercise 4: Shape the data
- Parse the `author_url` to create new column named `author`
- Sort the data by putting higher rates go first. If there are overlapping rates, try to put earlier years go first.
- **(Stretch Goal)** Examine how many books were published at each year and find lowest, highest rate of each year.

In [54]:
# your code here
# use many cells if you like to structure your code well
test_string = df_cleaned.author_url[0]
test_string

'https://www.goodreads.com/author/show/153394.Suzanne_Collins'

In [55]:
test_string.split('/')[-1].split('.')[1:][0]

'Suzanne_Collins'

In [56]:

def get_author(url):

    name = url.split('/')[-1].split('.')[1:][0]
     
    return name

In [57]:
df_cleaned['author'] = df_cleaned.author_url.map(get_author)
df_cleaned.author[0:5]

C:\Users\bartl\AppData\Local\Temp\ipykernel_23964\3669023917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['author'] = df_cleaned.author_url.map(get_author)

0    Suzanne_Collins
1        J_K_Rowling
2    Stephenie_Meyer
3         Harper_Lee
4        Jane_Austen
Name: author, dtype: object

In [60]:

#Sort the data by rating (descending) and then by year (ascending)
df_sorted = df_cleaned.sort_values(by=['rating', 'year'], ascending=[False, True])

#Count books per year, and find the lowest and highest rate for each year
books_per_year = df_cleaned.groupby('year')['rating'].agg(['count', 'min', 'max'])

# Display the results
print("Books per year with lowest and highest ratings:")
print(books_per_year)
"""genuinely don't know what went wrong. catasrofe"""

Books per year with lowest and highest ratings:
          count   min   max
year
-1500.0       1  3.60  3.60
-800.0        2  3.68  4.01
-560.0        1  4.03  4.03
-512.0        1  3.92  3.92
-500.0        1  4.06  4.06
...         ...   ...   ...
 2011.0     374  2.00  5.00
 2012.0     355  3.15  5.00
 2013.0     276  2.90  4.93
 2014.0      87  3.31  5.00
 unknown      5  3.71  4.61

[294 rows x 3 columns]

## Exercise 5: Saving the results
- Save the cleaned dataframe as 'hw-03-cleaned.csv' in data folder

In [61]:
# your code here
# use many cells if you like to structure your code well
books_per_year.to_csv('data/books_per_year_summary.csv')

## Exercise 6: Investigate the relationship between the number of reviews and the average rating for books in the dataset cleaned-goodreads.csv procided.

- Calculate the correlation coefficient. Give me a short definition of this coefficient
- Create a scatter plot showing the relationship between these two features.
- Based on the plot and the correlation, provide a brief interpretation of the relationship.

### Python Tools: Use pandas and numpy for correlation, and matplotlib or seaborn for the scatter plot.

In [63]:
# your code here
# use many cells if you like to structure your code well
df = pd.read_csv("data/cleaned-goodreads.csv", encoding='utf-8')
df

      rating  review_count        isbn         booktype                                         author_url  year                                                dir  rating_count                                               name           author                                             genres
0       4.40        136455  0439023483  good_reads:book  https://www.goodreads.com/author/show/153394.S...  2008                dir01/2767052-the-hunger-games.html       2958974            The Hunger Games (The Hunger Games, #1)  Suzanne_Collins  young-adult|science-fiction|dystopia|fantasy|s...
1       4.41         16648  0439358078  good_reads:book  https://www.goodreads.com/author/show/1077326....  2003  dir01/2.Harry_Potter_and_the_Order_of_the_Phoe...       1284478  Harry Potter and the Order of the Phoenix (Har...      J_K_Rowling  fantasy|young-adult|fiction|fantasy|magic|chil...
2       3.56         85746  0316015849  good_reads:book  https://www.goodreads.com/author/show/941441.S...  2005                          dir01/41865.Twilight.html       2579564                            Twilight (Twilight, #1)  Stephenie_Meyer  young-adult|fantasy|romance|paranormal|vampire...
3       4.23         47906  0061120081  good_reads:book  https://www.goodreads.com/author/show/1825.Har...  1960              dir01/2657.To_Kill_a_Mockingbird.html       2078123                              To Kill a Mockingbird       Harper_Lee  classics|fiction|historical-fiction|academic|s...
4       4.23         34772  0679783261  good_reads:book  https://www.goodreads.com/author/show/1265.Jan...  1813                dir01/1885.Pride_and_Prejudice.html       1388992                                Pride and Prejudice      Jane_Austen  classics|fiction|romance|historical-fiction|li...
...      ...           ...         ...              ...                                                ...   ...                                                ...           ...                                                ...              ...                                                ...
5988    4.17          2226  0767913736  good_reads:book  https://www.goodreads.com/author/show/44565.Ca...  2005                dir60/78508.The_River_of_Doubt.html         16618                                 The River of Doubt  Candice_Millard  history|non-fiction|biography|adventure|book-c...
5989    3.99           775  1416909427  good_reads:book  https://www.goodreads.com/author/show/151371.J...  2006                             dir60/259068.Shug.html          6179                                               Shug        Jenny_Han  young-adult|realistic-fiction|romance|contempo...
5990    3.78           540  1620612321  good_reads:book  https://www.goodreads.com/author/show/5761314....  2012                         dir60/13503247-flawed.html          2971                                             Flawed     Kate_Avelynn  contemporary|romance|young-adult|sociology|abu...
5991    3.91           281         NaN  good_reads:book  https://www.goodreads.com/author/show/1201952....  2006                                 dir60/2750008.html          3083              Ø£Ø³Ø¹Ø¯ Ø§Ù
Ø±Ø£Ø© ÙÙ Ø§ÙØ¹Ø§ÙÙ
    A_id_al_Qarni  religion|islam|religion|self-help|spirituality...
5992    4.35            61  0786929081  good_reads:book  https://www.goodreads.com/author/show/1023510....  2001  dir60/66677.Legacy_of_the_Drow_Collector_s_Edi...          3982  Legacy of the Drow Collector's Edition (Legacy...    R_A_Salvatore  fiction|fantasy|magic|science-fiction-fantasy|...

[5993 rows x 11 columns]

In [70]:
data = df

column1 = data['rating']
column2 = data['review_count']

correlation_coefficient = np.corrcoef(column1, column2)[0, 1]#don't know why it doesn't do anything haha

## Exercise 7: Calculate the following descriptive statistics for the numerical features (e.g., number of reviews, average rating, etc.):
- Mean
- Median
- Standard Deviation
- Range
- Create a histogram or box plot for at least one of the numerical features, highlighting any skewness or outliers.
    
### Python Tools: Use pandas for data manipulation and matplotlib or seaborn for visualization.

In [ ]:
# your code here
# use many cells if you like to structure your code well